=== adis992/Data-Access/Modul1-XML/02-country.dtd
<!--ovo su validaciona pravila xml dokumenta-->
<!ELEMENT root (country)*>  <!--u dtd fajlu znak * oznacava da se moze pojaviti 1 ili vise puta-->
<!ELEMENT country (name, capital, description)>  <!--u dtd fajlu name capital i desc. mogu se pojaviti samo jedanput jer nema druge oznake-->
<!ATTLIST country countryCode CDATA #IMPLIED >  <!--na ovaj nacin se dodaje atribut elem, countryCode je naziv atributa, cdata je tip atributa , a IMPLIED je pravilo koje se odnosi na vrijednost atributa -->
<!ELEMENT name (#PCDATA)> <!-- PCDATA, što je skraćenica za parsed character data, moze da sadrzi bilo koji textualni sadrzaj koji xml parser moze da cita-->
<!ELEMENT capital (#PCDATA)> <!---->
<!ELEMENT description (#PCDATA)> <!---->

=== adis992/Data-Access/Modul1-XML/02-countries.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02-country.xsd">
    <!--  primjer 1
<!DOCTYPE root SYSTEM "02-country.dtd">

    <country countryCode="sr">
        <name>Serbia</name>
        <capital>Belgrade</capital>
        <description>Serbia is.....</description>
    </country>
    <country countryCode="fr">
        <name>France</name>
        <capital>Paris</capital>
        <description>France is.....</description>
    </country>
</root>
-->

    <!--moderniji nacin primjer 2-->
    <country countryCode="sr">
        <name>Serbia</name>
        <capital>Belgrade</capital>
        <description>Serbia is.....</description>
    </country>
    <country countryCode="fr">
        <name>France</name>
        <capital>Paris</capital>
        <description>France is.....</description>
    </country>
</root>
